@startuml class_diagram

title クラス図
skinparam noteBackgroundColor #ffffe0

class "Asan" as Asan {
  - x: double
  - y: double
  --
  + moveRight(): void
}

class "Bsan" as Bsan {
  - x: double
  - y: double
  --
  + moveRight(): void
}

@enduml
